### ISSUE TITLE
Avast detected threat

### ISSUE THREAD

**Issue by davejkish** [HighGroundVision/Desolator#2]
Avast detects a threat when Installing the autodrafter.

http://imgur.com/a/5wvNI

**Comment by RGBKnights** [comment]
Thanks for your feedback. This a know issues. 

Currently we are listed a unknown publisher. We are currently working toward becoming a trusted publisher. This involves code signing and building a base of trust. Unfortunately this mean a less then stellar experience for a early adopters like yourself who help form that base of trust.
